### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by jedi-tester** [aviaryan/SublimeNotebook#2]
Getting following error when encrypting:
```
Traceback (most recent call last):
  File "./manager.py", line 33, in <module>
    update_file(encode, get_file_list(), key2)
  File "/Users/.../Documents/SublimeNotes/cryptlib.py", line 62, in update_file
    newData = funcptr(key, data)
  File "/Users/.../Documents/SublimeNotes/cryptlib.py", line 20, in encode
    return ENCODED_IDF + base64.urlsafe_b64encode("".join(enc).encode()).decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 0: ordinal not in range(128)
```

**Comment by aviaryan** [comment]
This project requires Python 3. Are you using Python 3?

**Comment by aviaryan** [comment]
Closing because of inactivity.
